# SPDX-FileCopyrightText: (c) 2021-2025 Jeff C. Jensen
# SPDX-License-Identifier: MIT
#
# Modifications Copyright (c) 2024 Xronos Inc.
# SPDX-License-Identifier: BSD-3-Clause
#
# This file contains portions from Jeff C. Jensen under MIT 
# and modifications by Xronos Inc. under BSD-3-Clause.
---
# boto3 is used by some Ansible AWS tasks (when run on the host)
- name: Install boto3
  become: true
  ansible.builtin.apt:
    pkg:
      - python3-boto3
      - python3-botocore

# enable Ansible to sudo as unprivileged user
- name: Install sudo & acl
  become: true
  ansible.builtin.apt:
    pkg:
      - sudo
      - acl

# enable ansible unzip module, as well as embedded unzip
# such as get_url
- name: Install compression & download tools
  become: true
  ansible.builtin.apt:
    pkg:
      - zip
      - unzip
      - gzip
      - curl
      - wget

# tools useful for parsing ansible module output
- name: Install utilities
  become: true
  ansible.builtin.apt:
    pkg:
      - jq
