---
- name: Install python3
  ansible.builtin.apt:
    pkg:
      - python3
    state: latest
  become: true

- name: Use python3 by default
  community.general.alternatives:
    name: python
    path: /usr/bin/python3
    link: /usr/bin/python
  become: true

- name: Install python3-pip
  ansible.builtin.apt:
    pkg:
      - virtualenv
      - python3-setuptools
      - python3-pip
    state: latest
  become: true

- name: Upgrade pip
  ansible.builtin.pip:
    name: pip
    state: latest
  become: true
