---
- name: Deploy quad9 resolv.conf
  ansible.builtin.copy:
    src:  dns-quad9-resolv.conf
    dest: /etc/resolv.conf
  become: true
  when: ubuntu_dns_quad9 | default(false) | bool

- name: Deploy system resolv.conf
  ansible.builtin.copy:
    src:  system-resolv.conf
    dest: /etc/resolv.conf
  become: true
  when: ubuntu_dns_system | default(false) | bool

- name: Check internet connectivity
  ansible.builtin.wait_for:
    host: google.com
    port: 80
    timeout: 10
