---
- name: Set timezone
  community.general.timezone:
    name: "{{ ubuntu_timezone }}"
  become: true

- name: Install ntp
  ansible.builtin.apt:
    pkg:   ntp
    state: latest
  become: true

- name: Enable ntp
  ansible.builtin.service:
    name: ntp
    state: started
    enabled: true
  become: true
